### ISSUE TITLE
whoami not providing account id

### ISSUE THREAD

**Issue by jswright61** [dnsimple/dnsimple-api-examples#2]
I followed your instructions for creating a user token in the web interface.
I placed that token in token.rb as directed.
When I run ./zone_records.rb example.com, it throws an exception because account in the response object is nil.

#<Dnsimple::Response:0x007fa4862d6630
 @data=
  #<Dnsimple::Struct::Whoami:0x007fa4862d6900
   @account=nil,
   @user=
    #<Dnsimple::Struct::User:0x007fa4862d6838
     @email="user@example.com",
     @id=12345>>,
 @http_response=
  {"data"=>
    {"user"=>
      {"id"=>12345,
       "email"=>"user@example.com",
       "created_at"=>"2016-01-15T12:15:36.956Z",
       "updated_at"=>"2016-11-16T11:13:15.498Z"},
     "account"=>nil}},
 @rate_limit=2400,
 @rate_limit_remaining=2399,
 @rate_limit_reset=2016-11-18 08:47:13 -0500>

**Comment by aeden** [comment]
You are absolutely correct that the README indicates you should generate a user token. There is actually a second token type, which is an account token. If you use a user token, then the user will be set and account will be nil in the whoami response. If you use an account token then you will get an account back from whoami and user will be nil.

Thus, I will

-  update the README to clarify the different tokens, and clarify which should be used in most cases (which is the account token)
- provide examples of each in the whoami example

**Comment by jswright61** [comment]
I'd love to help. I can do a PR if you want. I just need a tiny bit of guidance on where / how to create the account token.

Also, perhaps token.rb should be updated to include:
ACCOUNT_TOKEN = 'acct_token'
USER_TOKEN = 'usr_token'

And then scripts updated accordingly.

**Comment by aeden** [comment]
If you're willing and able, then go for it! :-)

**Comment by aeden** [comment]
Closing this as the README was updated by @jswright61
